## Hello there your International friendly vigilante is back online and we are going to go deep into the tensors today


In [1]:
##so apparently theres a way we can actually start creating random zeros with tensors

In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



hero = torch.zeros([4,5,6])

In [6]:
hero

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [7]:
##so we can also create tensors that for some reason takes ones and zeros and multiplies

In [8]:
villans = torch.ones([3,4,5])

In [9]:
villans


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [10]:
villans.dtype


torch.float32

In [11]:
###creating tensors in range

In [12]:
gojo = torch.arange(2,899998)

In [13]:
gojo


tensor([     2,      3,      4,  ..., 899995, 899996, 899997])

In [14]:
satoru = torch.arange(start = 12 , end = 567 , step=4)

In [15]:
satoru

tensor([ 12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,  56,  60,  64,
         68,  72,  76,  80,  84,  88,  92,  96, 100, 104, 108, 112, 116, 120,
        124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176,
        180, 184, 188, 192, 196, 200, 204, 208, 212, 216, 220, 224, 228, 232,
        236, 240, 244, 248, 252, 256, 260, 264, 268, 272, 276, 280, 284, 288,
        292, 296, 300, 304, 308, 312, 316, 320, 324, 328, 332, 336, 340, 344,
        348, 352, 356, 360, 364, 368, 372, 376, 380, 384, 388, 392, 396, 400,
        404, 408, 412, 416, 420, 424, 428, 432, 436, 440, 444, 448, 452, 456,
        460, 464, 468, 472, 476, 480, 484, 488, 492, 496, 500, 504, 508, 512,
        516, 520, 524, 528, 532, 536, 540, 544, 548, 552, 556, 560, 564])

###so apprantly i can absolutely create tensors based on the shapes i want and if i am too lazy to put the shape i can just be like copy the move like another tensor lol , so i am lazy at the moment cause i am busy understanding why dc is not producing good films lol , therefore i would be doing like function here

In [16]:
dc = torch.zeros_like(satoru)
dc

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### so i learnt about tensors with arange ( creates stuff from any number to your destination , then i can create new shapes and forms and link them together and i understood i could litreally add or create o and 1 tensors

In [17]:
print (satoru + gojo + hero + villans)

RuntimeError: The size of tensor a (139) must match the size of tensor b (899996) at non-singleton dimension 0

In [19]:
### see i made this mistake on purpose to make sure that others wont cause as you see this is
### is litreally like a maze u need to know the foundations of pytorch mate cause we do have to makee sure that
### yes what i am typing has to be dimension based

In [23]:
gojosatoru = torch.zeros(4,5,6)

In [24]:
tenjaku = torch.ones(4,5,6)

In [31]:
yuji = torch.arange(start=4,end=5,step=6)

### Tensor Datatypes

In [38]:
## 32 , 16 bit floating point data type

In [40]:
## Tensor datatypes are one of the 3 big errors we run into in pytorch
## 1. t not being right datatype
## 2. t is not right shape and another one is right device

In [45]:
got = torch.tensor([2,3,4])

In [46]:
got.dtype

torch.int64

In [47]:
got = got.type(torch.float32)

In [48]:
got

tensor([2., 3., 4.])

In [49]:
got = got.type(torch.complex64)

In [50]:
got

tensor([2.+0.j, 3.+0.j, 4.+0.j])

### Tensor Attributes lets see where this goes

In [52]:
## we be going to multiply different datatypes like mr heisenberg


jessie = torch.tensor([5,6,5],dtype=torch.int64)

In [58]:
pinkman = torch.tensor([4,5,90], dtype=torch.float32)

In [59]:
x=jessie+pinkman

In [60]:
x

tensor([ 9., 11., 95.])

In [61]:
y=jessie*pinkman

In [62]:
y


tensor([ 20.,  30., 450.])

In [67]:
z=x*y/x+y

In [68]:
z

tensor([ 40.,  60., 900.])

In [69]:
z1 = torch.rand(4,5,5)

In [71]:
z1.shape

torch.Size([4, 5, 5])

In [72]:
z1.size

<function Tensor.size>

In [73]:
z1.device

device(type='cpu')