In [1]:
### Tensor operations mate

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
zoro = torch.tensor([4,5,6,6])

In [4]:
zoro + 10

tensor([14, 15, 16, 16])

In [5]:
zoro + 10 - 10 *22 %3 *700


tensor([-686, -685, -684, -684])

In [6]:
## the basic arthemetics is again completed so lets do the matrix multiplication

In [7]:
hero = torch.tensor([8,8,6,5])

### Given below is the matrix multiplication that can be done and achieved through different ways

In [8]:
zoro * hero

tensor([32, 40, 36, 30])

In [9]:
zoro.matmul(hero)

tensor(138)

shape errors are somethiing that happens a lot in deep learning so keep that mind

and the resulting matrix always matches the shape of outer dimensioin

In [11]:
## the inner dimensions must match like (3,4) and (4,9) will work but the other one wont

In [15]:
z= torch.rand([4,9])
y = torch.rand([9,5])

z.matmul(y)

tensor([[1.3478, 1.7532, 1.3188, 1.7805, 0.8887],
        [2.2433, 2.4964, 1.9252, 2.4949, 1.8106],
        [2.0254, 1.7652, 1.6631, 2.0038, 1.5691],
        [1.2758, 1.5201, 1.0837, 1.5451, 1.2225]])

###shape errors are common in neural networks so keeping that aside shape errors are caused when dimensions dont match.

In [17]:
ragna = torch.tensor([[4,5,6],
                     [7,6,5],
                     [8,9,6]])

crimson = torch.tensor([[1,2,3],
                       [3,4,5],
                       [6,5,7]])

ragna*crimson

tensor([[ 4, 10, 18],
        [21, 24, 25],
        [48, 45, 42]])

In [18]:
ragna.mm(crimson)

tensor([[ 55,  58,  79],
        [ 55,  63,  86],
        [ 71,  82, 111]])

i am currently shocked i was expecting a shape error here but that aside if we ever run into errors lets run transpose of matrix

In [19]:
ragna.T

tensor([[4, 7, 8],
        [5, 6, 9],
        [6, 5, 6]])

In [20]:
crimson.T


tensor([[1, 3, 6],
        [2, 4, 5],
        [3, 5, 7]])

In [21]:
crimson.T.shape

torch.Size([3, 3])

omg i now get it , transpose of the inner dimensions through tensor transpose giving us a lot of easy method to work around the shape erros

In [23]:
hello = crimson.T.matmul(ragna.T)

aggregation function

In [24]:
torch.sum(hello)

tensor(660)

In [25]:
torch.min(hello)

tensor(55)

In [26]:
torch.max(hello)

tensor(111)

In [69]:
barbara = torch.arange(start=9,end=900,step=9)
gordon = torch.arange(start=8,end=800,step = 8)
robin=torch.arange(start=7,end=700,step=7)

barbara*gordon



tensor([    72,    288,    648,   1152,   1800,   2592,   3528,   4608,   5832,
          7200,   8712,  10368,  12168,  14112,  16200,  18432,  20808,  23328,
         25992,  28800,  31752,  34848,  38088,  41472,  45000,  48672,  52488,
         56448,  60552,  64800,  69192,  73728,  78408,  83232,  88200,  93312,
         98568, 103968, 109512, 115200, 121032, 127008, 133128, 139392, 145800,
        152352, 159048, 165888, 172872, 180000, 187272, 194688, 202248, 209952,
        217800, 225792, 233928, 242208, 250632, 259200, 267912, 276768, 285768,
        294912, 304200, 313632, 323208, 332928, 342792, 352800, 362952, 373248,
        383688, 394272, 405000, 415872, 426888, 438048, 449352, 460800, 472392,
        484128, 496008, 508032, 520200, 532512, 544968, 557568, 570312, 583200,
        596232, 609408, 622728, 636192, 649800, 663552, 677448, 691488, 705672])

In [70]:
h=torch.max(barbara).min(barbara)

In [71]:
yo=torch.max(gordon).min(gordon)

In [72]:
gi = torch.max(robin).min(robin)

In [73]:
print(h.shape)
print(yo.shape)
print(gi.shape)

torch.Size([99])
torch.Size([99])
torch.Size([99])


as i ran into the problem of having bad shape so i am doing this thing called.shape that helps me understand and play around with the data

In [74]:
torch.sum(h+yo+gi)

tensor(118800)

In [75]:
torch.max(h+yo+gi)

tensor(2376)

In [76]:
torch.min(h+yo+gi)

tensor(24)

Therefore we got the aggregation all right so whenever we see errors try changing the error with understanding where shape is and understand where u can work towards it through datatypes or transposing whatever u want

In [82]:
torch.mean(yo.type(torch.float32))

tensor(400.)

In [83]:
yo.argmin()

tensor(0)

In [84]:
yo.argmax()

tensor(98)

Alr this is the basics of aggregations and now lets start with reshaping ,squeezing and unsqueezing tensors


In [87]:
##reshaping - defines tensor in required shape
# view - return views like sql views
#stacking - combining / concatinating stacks on top each other (h/z)
#squeeze- removes id
#unsqueeze - adds 1d
#permute - returns of view with dimensions in a way

In [96]:
hellsing = torch.arange(start = 1 , end = 100 , step = 1)
hellsing.shape

torch.Size([99])

In [97]:
hellsing_unloaded = hellsing.reshape(3,33)

In [98]:
hellsing_unloaded.shape

torch.Size([3, 33])

In [103]:
hellsing_unloaded.view(11,9)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60, 61, 62, 63],
        [64, 65, 66, 67, 68, 69, 70, 71, 72],
        [73, 74, 75, 76, 77, 78, 79, 80, 81],
        [82, 83, 84, 85, 86, 87, 88, 89, 90],
        [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
hellsing_unloaded.squeeze

<function Tensor.squeeze>

In [106]:
hellsing_unloaded

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
         52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
        [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
         85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [107]:
hellsing_unloaded.shape

torch.Size([3, 33])

In [111]:
hu =hellsing_unloaded.reshape(11,9)

In [119]:
hu=hellsing_unloaded.squeeze
hu

<function Tensor.squeeze>

In [113]:
hu=hellsing_unloaded.shape

In [114]:
hu

torch.Size([3, 33])